#include "hedley.h"

#ifdef EIGHT_COMPILATION
#  define EIGHT_API HEDLEY_PUBLIC
#else
#  define EIGHT_API HEDLEY_IMPORT
#endif

#define EIGHT_VERSION_MAJOR 0
#define EIGHT_VERSION_MINOR 1
#define EIGHT_VERSION_REVISION 0

#define EIGHT_VERSION HEDLEY_ENCODE_VERSION(EIGHT_VERSION_MAJOR, EIGHT_VERSION_MINOR, EIGHT_VERSION_REVISION)

#define EIGHT_VERSION_0_1 HEDLEY_ENCODE_VERSION(0,1,0)

#if !defined(EIGHT_TARGET_VERSION)
#  define EIGHT_TARGET_VERSION EIGHT_VERSION
#endif
#if !defined(EIGHT_VERSION_MIN_REQUIRED)
#  define EIGHT_VERSION_MIN_REQUIRED EIGHT_TARGET_VERSION
#endif
#if !defined(EIGHT_VERSION_MAX_ALLOWED)
#  define EIGHT_VERSION_MAX_ALLOWED EIGHT_TARGET_VERSION
#endif

// #if EIGHT_VERSION_MIN_REQUIRED > EIGHT_VERSION_0_1
// #  define EIGHT_DEPRECATED_SINCE_1_1 HEDLEY_DEPRECATED(1.1)
// #  define EIGHT_DEPRECATED_SINCE_1_1_FOR(replacement) HEDLEY_DEPRECATED_FOR(1.1, replacement)
// #else
// #  define EIGHT_DEPRECATED_SINCE_1_1
// #  define EIGHT_DEPRECATED_SINCE_1_1_FOR(replacement)
// #endif

// #if EIGHT_VERSION_MAX_ALLOWED < EIGHT_VERSION_0_1
// #  define EIGHT_AVAILABLE_SINCE_1_1 HEDLEY_UNAVAILABLE(1.1)
// #else
// #  define EIGHT_AVAILABLE_SINCE_1_1
// #endif

// #if FOO_VERSION_MIN_REQUIRED > FOO_VERSION_1_2
//   #define FOO_DEPRECATED_SINCE_1_2 HEDLEY_DEPRECATED(1.2)
//   #define FOO_DEPRECATED_SINCE_1_2_FOR(replacement) HEDLEY_DEPRECATED_FOR(1.2, replacement)
// #else
//   #define FOO_DEPRECATED_SINCE_1_2
//   #define FOO_DEPRECATED_SINCE_1_2_FOR(replacement)
// #endif

// #if FOO_VERSION_MAX_ALLOWED < FOO_VERSION_1_2
//   #define FOO_AVAILABLE_SINCE_1_2 HEDLEY_UNAVAILABLE(1.2)
// #else
//   #define FOO_AVAILABLE_SINCE_1_2
// #endif
